name: Get fxserver latest release versions
on:
  schedule:
    - cron: '28 * * * *'
jobs:
  get-versions:
    name: Get fxserver latest release versions
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0
    - name: Build
      run: npm install
    - name: Scrape
      id: scrape
      env:
        LINUX_VERSIONS_FILE_PATH: ./data/linux-versions.json
        WINDOWS_VERSIONS_FILE_PATH: ./data/windows-versions.json
      run: npm start
    - name: Commit files
      id: commit
      if: |
        steps.scrape.outputs.windows-recommended ||
        steps.scrape.outputs.windows-latest ||
        steps.scrape.outputs.linux-recommended ||
        steps.scrape.outputs.linux-latest
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "[Auto] New FXServer versions" -a
    - name: Push changes
      if: steps.commit.outcome == 'success'
      uses: ad-m/github-push-action@v1.3.0
      with:
        token: ${{ github.token }}
        branch: ${{ github.ref }}
    - name: Trigger routmoute/fxserver
      if: steps.scrape.outputs.linux-latest || steps.scrape.outputs.linux-recommended
      uses: informaticsmatters/trigger-ci-action@v1
      with:
        ci-type: github-workflow-dispatch
        ci-owner: ${{ secrets.WORKFLOW_USER }}
        ci-repository: fxserver
        ci-ref: refs/heads/main
        ci-user: ${{ secrets.WORKFLOW_USER }}
        ci-user-token: ${{ secrets.WORKFLOW_TOKEN }}
        ci-name: New FXserver version released
        ci-inputs: >-
          latest=${{ steps.scrape.outputs.linux-latest }}
          latest_url=${{ steps.scrape.outputs.linux-latest_url }}
          recommended=${{ steps.scrape.outputs.linux-recommended }}
          recommended_url=${{ steps.scrape.outputs.linux-recommended_url }}
